### ISSUE TITLE
I like this idea! And some other talkings..

### ISSUE THREAD

**Issue by garywill** [algon-320/vime#3]
Hi @algon-320 , 

Just some talking ..

I like your idea to use vim on any text field!

I made a keyboard clicking screen project https://postimg.cc/n9767XYR (experimental)
I added your url to my list here https://github.com/garywill/vimouse#other-vi--keybinding-projects

btw, I'm having an idea: 
Saw you used XIM. Would implementing vim key features on IME itself be better?
Since there are some open source cross-platform IMEs, maybe an IME-vim without terminal and with being cross-platform would be great.
(I'm just shoot the breeze..)

**Comment by algon-320** [comment]
Hi @garywill,

Thank you for your comment! And thank you for adding a link to my project in your page :wink:

As you said, that's maybe possible to build an IME that can process vim-like keybindings by itself. Actually, I was also thinking such IMEs when I came up with this project.

In terms of simplicity and portability, the current architecture might look too complicated as it requires a terminal emulator. But, there are some pros in this architecture IMO:
- First, this architecture allows us to use authentic Vim, which means we can use Vim with our favorite plugins and easily customize the behavior.
- Second, we can also use other text editors, not only Vim. I like this feature.
- Third, we can use other well-made IMEs for inputting non-English sentences. Isn't it so hard to implement a smart conversion engine by ourselves? (This is not specific to this architecture, so maybe you can "chain" multiple IMEs or use some libraries in the IME-vim.)

Honestly, I'm not really interested in making such an IME, but anyone can try and it would be useful if the IME is usable in multi-platform.

BTW:

> I made a keyboard clicking screen project https://postimg.cc/n9767XYR (experimental)

That's cool! I'm personally interested in how your app works in X11.

Thanks!

**Comment by garywill** [comment]
> I'm personally interested in how your app works in X11.

Thanks to those cross-platform python libraries, I made it work easily with 300 lines python code:

1. take screenshot
2. use opencv to pick "objects"
3. use tk to show key badges
4. use pynput to "block" and listen all key events
5. use pynput, also, to trigger click when user choose

(not sure if they will be replaced by others in future)

> Isn't it so hard to implement a smart conversion engine by ourselves? (This is not specific to this architecture, so maybe you can "chain" multiple IMEs or use some libraries in the IME-vim.)

Yes you're right. 
And switching or chaining IMEs may be hard for us.

I have another idea, also:

Like I used pynput to "block and listen" desktop keyboard events in viScreenMouse, a "fake vim IME" can be implemented by doing so, when implementing vim's normal/visual mode. So we don't have to do any true IME-related programming

Once I get free time I may give that idea a try

**Comment by algon-320** [comment]
> use opencv to pick "objects"

You mean you do a kind of object detection and collects regions that look clickable in the screen?

> Once I get free time I may give that idea a try

Good luck, that should be a lot of fun!

**Comment by garywill** [comment]
> You mean you do a kind of object detection and collects regions that look clickable in the screen?

Yes. MSER algorithm ( ctually, I'm newbie to computer vision... hoping an expert stand out to help me)

 Leant from here https://dsp.stackexchange.com/questions/1657/how-can-i-detect-elements-of-gui-using-opencv

**Comment by algon-320** [comment]
Thank you for sharing. That's interesting. I'm wondering the fuzziness of the algorithm could be somewhat problematic for the usability?

This is also completely different project, but my window manager I made before had a feature that allows me to move the cursor position up/down/left/right by hitting special key combinations. It might be more useful if your application has a similar feature.

Let me close this now. Please feel free to open another issue (or reopen this) if you have another great idea for improving this project!

**Comment by garywill** [comment]
> I'm wondering the fuzziness of the algorithm could be somewhat problematic for the usability?

Yes there are problems. So that's currently in experimental stage. Hope in the future we can combine vision (AI) and GUI buttons API to make a true useful keyboard mouse.

> window manager I made before had a feature that allows me to move the cursor position up/down/left/right by hitting special key combinations

Talking about using keyboard to move mouse cursor, I've tried using a game controller (digital and analog). I didn't get a good result feeling. It felt really hard to "aim" a button (I didn't have a good gaming technique? lol)

What's your experience using that feature?

I'll consider adding such a  feature. Still personally I think people won't use like that as main feature
